name: foxy-img-proxy
services:
    foxy:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./docker.config.json:/source.config.json:ro
            - ./presets.json:/presets.json
            - ./.env:/.env:ro
            - ./google.json:/google.json:ro