name: foxy-img-proxy
services:
    foxy:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./configs/dev/docker.config.json:/source.config.json:ro
            - ./configs/presets.json:/presets.json
            - ./docker.env:/.env:ro
            - ./configs/dev/google.json:/google.json:ro
            - ./models:/models:ro