name: foxy
networks:
  foxy_network:
    driver: bridge
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - foxy_network
    ports:
      - "15432:5432"
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - foxy_network
    ports:
      - "16379:6379"
  static_files:
    image: flashspys/nginx-static
    container_name: static_files
    ports:
      - 8081:80
    volumes:
      - /Volumes/Projects/Archive/Images:/static
